version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/project

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=administrator
    ports:
      - "5432:5432"
    volumes:
      - ./db/:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./static:/etc/nginx/static

